### ISSUE TITLE
不兼容ssr哦

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [devilwjp/uni-crazy-router#25]
```base
uni-crazy-router doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.​
(node:74293) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```
```base
ReferenceError: history is not defined
    at /node_modules/.pnpm/uni-crazy-router@1.1.3_npj5xmp7zps2xcx47ncgjpdliu/node_modules/uni-crazy-router/dist/index.js:1:12291
    at async instantiateModule (file:///demo/node_modules/.pnpm/vite@4.0.3_ovmyjmuuyckt3r3gpaexj2onji/node_modules/vite/dist/node/chunks/dep-0bae2027.js:52198:9)
```
```js
// vite ssr配置
ssr: {
  noExternal: ['uni-crazy-router']
},
```

**Comment by devilwjp** [comment]
@UphkcRNqmafQWcSSSSSS 差个插件本来就是只对csr有效的，是在浏览器运行的

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
> @UphkcRNqmafQWcSSSSSS 差个插件本来就是只对csr有效的，是在浏览器运行的
收到，放弃ssr了。
